version: 2.1

orbs:
  win: circleci/windows@2.0.0
jobs:
  build_and_test:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing Build System
          command: 'apt-get update && apt-get install -y git build-essential libboost-system-dev cmake python2.7'
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Creating Build Files
          command: 'cd svgnative && cmake -Bbuild/linux -H.'
      - run:
          name: Creating Binary Files
          command: 'cd svgnative && cmake --build build/linux'
      - run:
          name: Run tests
          command: 'cd svgnative && /usr/bin/python2.7 script/runTest.py --test=test'
  build_with_clang:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing Build System
          command: 'apt-get update && apt-get install -y git build-essential libboost-system-dev clang cmake python2.7'
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Creating Build Files
          command: 'cd svgnative && cmake -Bbuild/linux -H. -DCMAKE_CXX_COMPILER=clang -DLIB_ONLY=ON'
      - run:
          name: Creating Binary Files
          command: 'cd svgnative && cmake --build build/linux'
  build_with_style_support:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing Build System
          command: 'apt-get update && apt-get install -y git build-essential libboost-system-dev cmake python2.7'
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Creating Build Files
          command: 'cd svgnative && cmake -Bbuild/linux -H. -DSTYLE=ON'
      - run:
          name: Creating Binary Files
          command: 'cd svgnative && cmake --build build/linux'
  build_with_cocoa:
    macos:
      xcode: "10.3.0"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Installing dependencies
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake boost
      - run:
          name: Creating Build Files
          command: 'cd svgnative && cmake -Bbuild/mac -H. -DCG=ON'
      - run:
          name: Creating Binary Files
          command: 'cd svgnative && cmake --build build/mac'
  build_with_windraw:
    executor: win/default
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Installing dependencies
          command: |
            Invoke-RestMethod -Uri https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-win64-x64.zip -Method Get -OutFile cmake.zip
            Expand-Archive .\cmake.zip cmake

      - run:
          name: Build windraw
          command: |
            cd third_party/
            .\cmake\cmake-3.15.4-win64-x64\bin cmake.exe -Bbuild/win64 -H. -G "Visual Studio 16 2019" -DWINDRAWLIB_BUILD_EXAMPLES=OFF
            .\cmake\cmake-3.15.4-win64-x64\bin cmake.exe --build build/win64
      - run:
          name: Creating Build Files
          command: |
            cd svgnative
            .\cmake\cmake-3.15.4-win64-x64\bin cmake.exe -Bbuild/win64 -H. -DWINDRAW=ON
      - run:
          name: Creating Binary Files
          command: |
            cd svgnative
            .\cmake\cmake-3.15.4-win64-x64\bin cmake.exe --build build/win64
workflows:
  version: 2
  run_all_tests:
    jobs:
      - build_and_test
      - build_with_style_support
      - build_with_clang
      - build_with_cocoa
      - build_with_windraw
